In [266]:
import pandas as pd
import numpy as np
make='model_4'

In [267]:
#returns ovr table with Temperature, Htot, hydrogen density, e density, and OVI density

vari='.ovr'
table=pd.read_csv('{0}{1}'.format(make, vari),delimiter='	')
ovr=table.loc[:,['#depth','Te','Htot','hden','eden','O5']]
Temp=np.log10(ovr.loc[0,"Te"])
ovr

          #depth       Te          Htot    hden     eden       O5
0   7.905690e+17  10000.0  1.166000e-31  0.0001  0.00012  0.14035
1   3.083220e+18  10000.0  1.166000e-31  0.0001  0.00012  0.14035
2   5.937180e+18  10000.0  1.166000e-31  0.0001  0.00012  0.14035
3   8.505740e+18  10000.0  1.166000e-31  0.0001  0.00012  0.14035
4   1.081740e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
5   1.289800e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
6   1.477050e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
7   1.645570e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
8   1.797240e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
9   1.933740e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
10  2.056600e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
11  2.167170e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
12  2.266680e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
13  2.356240e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
14  2.436840e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
15  2.509380e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
16  2.574670e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
17  2.633430e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
18  2.686320e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
19  2.733910e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
20  2.776750e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
21  2.815300e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
22  2.850000e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
23  2.882250e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
24  2.913870e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
25  2.945490e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
26  2.977120e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
27  3.008740e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
28  3.040360e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
29  3.071980e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
30  3.103610e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
31  3.135230e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035
32  3.156660e+19  10000.0  1.166000e-31  0.0001  0.00012  0.14035

In [268]:
#returns emis table with Emissivity of H 1 4861.33A, H 1 6562.81A, O 6 1031.00A, O 6 1037.62A

vari='.emis'
emis=pd.read_csv('{0}{1}'.format(make, vari),delimiter='	')
emis.columns=['#depth','H1-4861.33A', 'H1-6562.81A', 'O6-1031.91A','O6-1037.62A']

#isolates the 1031 and 1037 lines as independent tables
tenthirtyone= emis.loc[:,'O6-1031.91A'] 
tenthirtyseven= emis.loc[:,'O6-1037.62A']

#tenthirtyone
#tenthirtyseven
emis

          #depth   H1-4861.33A   H1-6562.81A   O6-1031.91A   O6-1037.62A
0   7.905690e+17  1.514500e-33  4.173800e-33  6.859400e-32  3.433200e-32
1   3.083220e+18  1.514400e-33  4.173800e-33  6.859400e-32  3.433200e-32
2   5.937180e+18  1.514400e-33  4.173700e-33  6.859400e-32  3.433200e-32
3   8.505740e+18  1.514400e-33  4.173600e-33  6.858400e-32  3.433200e-32
4   1.081740e+19  1.514400e-33  4.173500e-33  6.857100e-32  3.433200e-32
5   1.289800e+19  1.514400e-33  4.173500e-33  6.856000e-32  3.433100e-32
6   1.477050e+19  1.514400e-33  4.173400e-33  6.855000e-32  3.432800e-32
7   1.645570e+19  1.514400e-33  4.173400e-33  6.854000e-32  3.432600e-32
8   1.797240e+19  1.514400e-33  4.173300e-33  6.853200e-32  3.432400e-32
9   1.933740e+19  1.514400e-33  4.173300e-33  6.852400e-32  3.432200e-32
10  2.056600e+19  1.514400e-33  4.173300e-33  6.851800e-32  3.432000e-32
11  2.167170e+19  1.514400e-33  4.173200e-33  6.851200e-32  3.431900e-32
12  2.266680e+19  1.514400e-33  4.173200e-33  6.850600e-32  3.431700e-32
13  2.356240e+19  1.514400e-33  4.173200e-33  6.850100e-32  3.431600e-32
14  2.436840e+19  1.514400e-33  4.173200e-33  6.849700e-32  3.431500e-32
15  2.509380e+19  1.514400e-33  4.173100e-33  6.849300e-32  3.431400e-32
16  2.574670e+19  1.514400e-33  4.173100e-33  6.848900e-32  3.431300e-32
17  2.633430e+19  1.514400e-33  4.173100e-33  6.848600e-32  3.431200e-32
18  2.686320e+19  1.514300e-33  4.173100e-33  6.848300e-32  3.431100e-32
19  2.733910e+19  1.514300e-33  4.173100e-33  6.848000e-32  3.431100e-32
20  2.776750e+19  1.514300e-33  4.173100e-33  6.847800e-32  3.431000e-32
21  2.815300e+19  1.514300e-33  4.173100e-33  6.847600e-32  3.431000e-32
22  2.850000e+19  1.514300e-33  4.173000e-33  6.847400e-32  3.430900e-32
23  2.882250e+19  1.514300e-33  4.173000e-33  6.847200e-32  3.430900e-32
24  2.913870e+19  1.514300e-33  4.173000e-33  6.847100e-32  3.430800e-32
25  2.945490e+19  1.514300e-33  4.173000e-33  6.846900e-32  3.430800e-32
26  2.977120e+19  1.514300e-33  4.173000e-33  6.846700e-32  3.430700e-32
27  3.008740e+19  1.514300e-33  4.173000e-33  6.846600e-32  3.430700e-32
28  3.040360e+19  1.514300e-33  4.173000e-33  6.846400e-32  3.430700e-32
29  3.071980e+19  1.514300e-33  4.173000e-33  6.846200e-32  3.430600e-32
30  3.103610e+19  1.514300e-33  4.173000e-33  6.846100e-32  3.430600e-32
31  3.135230e+19  1.514300e-33  4.173000e-33  6.845900e-32  3.430500e-32
32  3.156660e+19  1.514300e-33  4.173000e-33  6.845800e-32  3.430500e-32

In [269]:
#returns eleH table with H	H+	H2 probabilites for each zone

vari='.ele_H'
eleH=pd.read_csv('{0}{1}'.format(make, vari),delimiter='	')
#print(eleH)
#returns eleO table with O	O+	O+2	O+3	O+4	O+5	O+6	O+7	O+8	O[1]	O[2]	O[3] probabilites for each zone
vari='.ele_O'
eleO=pd.read_csv('{0}{1}'.format(make,vari),delimiter='	')
#eleO

In [270]:
#returns table OVI_prob with OVI probabilites for each zone

OVI_prob = eleO.loc[:,['#depth', 'O+5']]
#OVI_prob

In [271]:
#returns single float of each value

O6frac=np.average(OVI_prob.loc[:,'O+5'].values)
#O6total=np.average(ovr.loc[:,'eden'].values)
eden=np.average(ovr.loc[:,'eden'].values)
emis1031=np.average(tenthirtyone.values)
emis1037=np.average(tenthirtyseven.values)
hden=np.average(ovr.loc[:,'hden'].values)

print('The OVI fraction is',O6frac)
#print('OVI total is',O6total)
print('The electron density is',eden)
print('The emissivity of OVI1031 is',emis1031)
print('The emissivity of OVI1037 is',emis1037)

The OVI fraction is 0.35700000000000004
The electron density is 0.00011989060606060608
The emissivity of OVI1031 is 6.850560606060605e-32
The emissivity of OVI1037 is 3.4316242424242424e-32

In [272]:
#number of oxygnVI
Noxy_Sol=10**-3.309
Zsol=10**-1
nOVI=O6frac*Zsol*Noxy_Sol
print('nOVI is',nOVI)
length=ovr.loc[:,"#depth"].max() -  ovr.loc[:,"#depth"].min()
N_OVI=nOVI*length
print('Column density of OVI is',N_OVI)

nOVI is 1.7525411178647926e-05
Column density of OVI is 539362597721815.1

In [273]:
#MassTot 7.40e-09  (gm/cm^2) ???

In [274]:
#intensity
inten= ((emis1031+emis1037) * length )/(4*np.pi)
inten

2.5181880222688087e-13

In [275]:
#overall values
print('For temperature base 10 to the',Temp,'power we get:')
print('OVI fraction:',O6frac)
print('electron density:',eden)
print('hydrogren density:',hden)

For temperature base 10 to the 4.0 power we get:
OVI fraction: 0.35700000000000004
electron density: 0.00011989060606060608
hydrogren density: 0.0001

In [276]:
#overall values
print('For temperature base 10 to the',Temp,'power we get:')
print('OVI fraction:',O6frac)
print('electron density:',eden)
print('hydrogren density:',hden)

For temperature base 10 to the 4.0 power we get:
OVI fraction: 0.35700000000000004
electron density: 0.00011989060606060608
hydrogren density: 0.0001

In [277]:
SimuDatKeyset=['H Density Log /cm^3','e Density Log /cm^3','OVI Probability','OVI 1031+1037 Emis']
SimnDat=[hden, eden,O6frac,emis1031+emis1037]
matrix={SimuDatKeyset[0]:[SimnDat[0]],SimuDatKeyset[1]:[SimnDat[1]],SimuDatKeyset[2]:[SimnDat[2]],SimuDatKeyset[3]:[SimnDat[3]]}

# SAVE

In [237]:
meta=pd.DataFrame(data=matrix,index={f"Temp:1e{Temp:1.1f} K , hden: {np.log10(hden):1.1f}"}).transpose()
#meta.rename(index={'Temp'})
meta

                     Temp:1e4.0 K , hden: -2.5
H Density Log /cm^3               3.162300e-03
e Density Log /cm^3               3.688852e-03
OVI Probability                   5.240000e-03
OVI 1031+1037 Emis                4.783061e-32

In [278]:
SimnDat=[hden, eden,O6frac,emis1031+emis1037]

In [ ]:
location=0

In [279]:
location=location+1
meta.insert(location,f"Temp:1e{Temp:1.1f} K , hden: {np.log10(hden):1.1f}",SimnDat)

In [280]:
meta

,"Temp:1e4.0 K , hden: -2.5","Temp:1e4.0 K , hden: -3.0","Temp:1e4.0 K , hden: -3.5","Temp:1e4.0 K , hden: -4.0"
H Density Log /cm^3,3.162300e-03,1.000000e-03,3.162300e-04,1.000000e-04
e Density Log /cm^3,3.688852e-03,1.186512e-03,3.780803e-04,1.198906e-04
OVI Probability,5.240000e-03,5.200909e-02,2.490000e-01,3.570000e-01
OVI 1031+1037 Emis,4.783061e-32,1.502270e-31,2.273631e-31,1.028218e-31

In [281]:
meta.to_csv('./CloudyDataTables/Temp(4)hden-(2.5-4).csv',index=True)